export const SHOW_EMPLOYEES = 'SHOW_EMPLOYEES';
export const SHOW_EMPLOYEE_MANAGERS = 'SHOW_MANAGERS';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_MANAGER = 'ADD_MANAGER';